description: |
  This configuration is a sample for a retirement planning scenario.

  We imagine the 'perfect' retirement: starting saving at 20 years old, and saving 5% of their income.

num_simulations: 5

life_phases:
  - name: Early Career
    age: 20
    annual_income: 40000
    annual_expenses: 35000
    annual_investment: 2000
    investment_allocation:
      savings: 0.5
      retirement: 0.5
    actions:
      - type: grant_asset
        name: savings
        config:
          type: basic_asset
          params:
            initial_investment: 1000
            expected_return: 0.04
            volatility: 0.05
      - type: grant_asset
        name: retirement
        config:
          type: stock_portfolio
          params:
            initial_investment: 1000
            portfolio_mix:
              VTSAX: 0.90 # Vanguard Total Stock Market Index Fund (stocks)
              VBTLX: 0.10 # Vanguard Total Bond Market Index Fund (bonds)

  - name: Better Job
    age: 30
    annual_income: 80000
    annual_expenses: 65000
    annual_investment: 5000
    investment_allocation:
      retirement: 1.0

  - name: Latter Career
    age: 50
    annual_income: 95000
    annual_expenses: 70000
    annual_investment: 10000
    investment_allocation:
      retirement: 0.8
      savings: 0.2
    actions:
      - type: modify_asset
        name: retirement
        updates:
          portfolio_mix:
            VTSAX: 0.60 # Vanguard Total Stock Market Index Fund (stocks)
            VBTLX: 0.40 # Vanguard Total Bond Market Index Fund (bonds)

  - name: Retirement
    age: 65
    annual_income: 0
    annual_expenses: 50000
    annual_investment: 0
