description: |
  This configuration is a sample for a retirement planning scenario.

  We imagine the 'perfect' retirement: starting saving at 20 years old, and saving 5% of their income.

num_simulations: 100
starting_age: 20

life_phases:
  - name: Early Career
    duration: 10
    annual_income: 40000
    annual_expenses: 35000
    annual_investment: 2000
    investment_allocation:
      stocks: 1.0

  - name: Better Job
    duration: 20
    annual_income: 80000
    annual_expenses: 65000
    annual_investment: 5000
    investment_allocation:
      stocks: 1.0

  - name: Latter Career
    duration: 15
    annual_income: 95000
    annual_expenses: 70000
    annual_investment: 10000
    investment_allocation:
      stocks: 0.8
      emergency_fund: 0.2
    actions:
      - type: modify_asset
        name: stocks
        updates:
          portfolio_mix:
            VTSAX: 0.60 # Vanguard Total Stock Market Index Fund (stocks)
            VBTLX: 0.40 # Vanguard Total Bond Market Index Fund (bonds)

  - name: Retirement
    duration: 25
    annual_income: 0
    annual_expenses: 50000
    annual_investment: 0

asset_classes:
  stocks:
    type: stock_portfolio
    params:
      initial_investment: 1000
      portfolio_mix:
        VTSAX: 0.90 # Vanguard Total Stock Market Index Fund (stocks)
        VBTLX: 0.10 # Vanguard Total Bond Market Index Fund (bonds)
  emergency_fund:
    type: basic_asset
    params:
      initial_investment: 1000
      expected_return: 0.041
      volatility: 0.005

draw_priority: ["emergency_fund", "stocks", "real_estate"]
