description: |
  This configuration is a sample for a retirement planning scenario.

  We imagine the 'perfect' retirement: starting saving at 20 years old, and saving 5% of their income.
starting_age: 20
num_years: 60
fulltime_years: 40
investment_per_year: 5_000
parttime_years: 5
parttime_income: 35_000
social_security: 30_000
expected_draw: 100_000
asset_classes:
  stocks:
    initial_investment: 0
    portfolio_mix:
      VFIAX: 0.06
      VIMAX: 0.08
      VMLUX: 0.18
      VTCLX: 0.39
      VTMGX: 0.13
      VTMSX: 0.09
      VWIUX: 0.12
  savings:
    # lets just assume for now I manage to sell half what I have as something stable.
    initial_investment: 5_000
    expected_return: 0.041
    volatility: 0.005
draw_priority: ["savings", "stocks"]
